kind: ConfigMap
apiVersion: v1
metadata:
  name: fabric8-cd
  labels:
    fabric8.io/kind: package
    provider: fabric8.io
    version: ${project.version}
data:
  metadata-url: http://central.maven.org/maven2/io/fabric8/tenant/packages/fabric8-cd/maven-metadata.xml
  package-url-prefix: http://central.maven.org/maven2/io/fabric8/tenant/packages/fabric8-cd/%[1]s/fabric8-cd-%[1]s-

